# Generated by Django 4.1 on 2022-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('processo', models.CharField(max_length=100, verbose_name='Processo')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('inicio', models.DateField(verbose_name='Data de Início')),
                ('termino', models.DateField(verbose_name='Data de Término')),
                ('tempo_restante', models.IntegerField(verbose_name='Tempo restante')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('observacao', models.TextField(verbose_name='Observação')),
            ],
            options={
                'ordering': ['inicio', 'data_cadastro'],
            },
        ),
    ]
