# Generated by Django 4.1 on 2022-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('cnpj', models.TextField(verbose_name='CNPJ')),
                ('nome_fantasia', models.TextField(max_length=100, verbose_name='Nome Fantasia')),
                ('razao_social', models.TextField(max_length=100, verbose_name='Razão Social')),
                ('responsavel', models.TextField(max_length=150, verbose_name='Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['data_cadastro', 'nome_fantasia'],
            },
        ),
    ]
