# Generated by Django 4.1 on 2022-08-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0002_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['data_cadastro', 'empresa']},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_fantasia',
            new_name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='setor',
            field=models.CharField(blank=True, choices=[('al', 'Alimentação'), ('tr', 'Transporte'), ('ss', 'Saúde'), ('co', 'Comércio'), ('c2', 'Comunicações'), ('sf', 'Serviços financeiros'), ('ti', 'TI'), ('ou', 'Outros')], default='----', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='processos',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proc.empresa'),
        ),
    ]
