# Generated by Django 4.1 on 2022-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0003_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=30, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.CharField(max_length=150, verbose_name='Responsável'),
        ),
    ]
