# Generated by Django 4.1 on 2022-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0005_processos_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='tempo_restante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo restante'),
        ),
    ]
