# Generated by Django 4.1 on 2022-10-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0006_alter_processos_tempo_restante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='setor',
            field=models.CharField(blank=True, choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Saúde', 'Saúde'), ('Comércio', 'Comércio'), ('Comunicações', 'Comunicações'), ('Serviços financeiros', 'Serviços financeiros'), ('TI', 'TI'), ('Outros', 'Outros')], default='----', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processos',
            name='garantia',
            field=models.IntegerField(blank=True, help_text='Em meses', null=True, verbose_name='Garantia'),
        ),
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('nr_bem', models.CharField(max_length=100, verbose_name='Patrimônio')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('conta', models.CharField(max_length=100, verbose_name='Conta')),
                ('centro_custo', models.CharField(blank=True, choices=[('Administrativo', 'Administrativo'), ('Técnico', 'Técnico')], default='Administrativo', max_length=100, null=True)),
                ('local', models.CharField(blank=True, choices=[('Sala Administrativo', 'Sala Administrativo'), ('Sala Técnico', 'Sala Técnico'), ('Sala Reunião', 'Sala Reunião'), ('Diretoria Administrativa', 'Diretoria Administrativa'), ('Diretoria Técnica', 'Diretoria Técnica'), ('Sala Secretário Executivo', 'Sala Secretário Executivo')], default='Sala Administrativo', max_length=100, null=True)),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('vlr_custo', models.FloatField()),
                ('vlr_residual_desc', models.FloatField()),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proc.empresa', verbose_name='Fornecedor')),
            ],
            options={
                'ordering': ['data_cadastro', 'nr_bem'],
            },
        ),
    ]
