# Generated by Django 4.1 on 2022-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0007_alter_empresa_setor_alter_processos_garantia_ativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='vlr_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo'),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='vlr_residual_desc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vlr Residual de Descarte'),
        ),
    ]
