# Generated by Django 4.1 on 2022-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0009_remove_ativos_descricao_ativos_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='notafiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='ativos',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
