# Generated by Django 4.1 on 2022-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0010_ativos_notafiscal_ativos_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='conta',
            field=models.CharField(blank=True, choices=[('Moveis e Utensilios', 'Moveis e Utensilios'), ('Equipamentos de Informática', 'Equipamentos de Informática'), ('Veículos', 'Veículos'), ('Máquinas e Equipamentos', 'Máquinas e Equipamentos')], default='------', max_length=200, null=True, verbose_name='Dotação'),
        ),
    ]
