# Generated by Django 4.1 on 2022-10-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0012_alter_ativos_centro_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='local',
            field=models.CharField(blank=True, choices=[('Sala Administrativo', 'Sala Administrativo'), ('Sala Técnico', 'Sala Técnico'), ('Sala Reunião', 'Sala Reunião'), ('Área Comum', 'Área Comum'), ('Diretoria Administrativa', 'Diretoria Administrativa'), ('Diretoria Técnica', 'Diretoria Técnica'), ('Sala Secretário Executivo', 'Sala Secretário Executivo')], default='Sala Administrativo', max_length=100, null=True),
        ),
    ]
