# Generated by Django 4.1 on 2022-10-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0013_alter_ativos_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-data_cadastro', 'empresa']},
        ),
        migrations.RemoveField(
            model_name='processos',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='processo',
            field=models.CharField(max_length=100, null=True, verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='processos',
            name='anexo',
            field=models.FileField(null=True, upload_to='', verbose_name='Arquivo do Processo'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proc.empresa'),
        ),
    ]
