# Generated by Django 4.1 on 2022-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0014_alter_empresa_options_remove_processos_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(blank=True, help_text='Breve descrição do documento', null=True, upload_to='', verbose_name='Documento')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('publicado', models.BooleanField(default=False)),
                ('categoria', models.CharField(blank=True, choices=[('Contas', 'Contas'), ('Contratos', 'Contratos'), ('Prestação de Contas', 'Prestação de Contas'), ('Informativo', 'Informativo')], default='----', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
