# Generated by Django 4.1 on 2022-10-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0016_alter_noticias_documento_alter_processos_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proc.empresa'),
        ),
    ]
